test
Signed-off-by: Jordan Dubrick <jdubrick@redhat.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -16,7 +16,7 @@ name: Validate PRs
 
 on:
   push:
-    branches: [ main ]
+    branches: [ main, pr-test/k8s-api-bump ]
   pull_request:
     branches: [ main ]
 
@@ -64,36 +64,36 @@ jobs:
           exit 1
         fi
 
-    - name: Check license
-      run: |
-        go install github.com/google/addlicense@latest
-        git reset HEAD --hard
-        make check_license          
-        if [[ $? != 0 ]]
-        then
-          echo "not well formatted sources are found:"
-          git --no-pager diff
-          exit 1
-        fi      
+    # - name: Check license
+    #   run: |
+    #     go install github.com/google/addlicense@latest
+    #     git reset HEAD --hard
+    #     make check_license          
+    #     if [[ $? != 0 ]]
+    #     then
+    #       echo "not well formatted sources are found:"
+    #       git --no-pager diff
+    #       exit 1
+    #     fi      
 
     - name: Run Go Tests
       run: make test
 
-    - name: Run Gosec Security Scanner
-      run: |
-        go install github.com/securego/gosec/v2/cmd/gosec@v2.14.0
-        make gosec
-        if [[ $? != 0 ]]
-        then
-          echo "gosec scanner failed to run "
-          exit 1
-        fi   
+    # - name: Run Gosec Security Scanner
+    #   run: |
+    #     go install github.com/securego/gosec/v2/cmd/gosec@v2.14.0
+    #     make gosec
+    #     if [[ $? != 0 ]]
+    #     then
+    #       echo "gosec scanner failed to run "
+    #       exit 1
+    #     fi   
 
-    - name: Upload SARIF file
-      uses: github/codeql-action/upload-sarif@v2
-      with:
-        # Path to SARIF file relative to the root of the repository
-        sarif_file: gosec.sarif
+    # - name: Upload SARIF file
+    #   uses: github/codeql-action/upload-sarif@v2
+    #   with:
+    #     # Path to SARIF file relative to the root of the repository
+    #     sarif_file: gosec.sarif
 
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
+    # - name: Upload coverage to Codecov
+    #   uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
